# Generated by Django 5.1.7 on 2026-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], db_index=True, max_length=20)),
                ('parameters', models.JSONField(help_text='Command parameters')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], db_index=True, default='SENT', max_length=20)),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('command_type', models.CharField(choices=[('CHANGE_MODE', 'Change Mode'), ('PAYLOAD_POWER', 'Payload Power'), ('ADCS_CONTROL', 'ADCS Control'), ('TAKE_PICTURE', 'Take Picture'), ('THERMAL_CONTROL', 'Thermal Control'), ('POWER_LINE', 'Power Line'), ('DEPLOY_ANTENNA', 'Deploy Antenna'), ('RECALIBRATE_SENSOR', 'Recalibrate Sensor'), ('SOFTWARE_UPDATE', 'Software Update')], db_index=True, max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'command_type'], name='control_com_status_174fee_idx'), models.Index(fields=['subsystem', 'command_type'], name='control_com_subsyst_de8a9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['severity', 'timestamp'], name='control_eve_severit_8f292d_idx'), models.Index(fields=['subsystem', 'severity'], name='control_eve_subsyst_cb2c67_idx'), models.Index(fields=['code'], name='control_eve_code_430dea_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version', models.CharField(max_length=20)),
                ('checksum', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'indexes': [models.Index(fields=['verified', 'uploaded_at'], name='control_sof_verifie_f88726_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], db_index=True, max_length=20)),
                ('state', models.JSONField(help_text='Current state as JSON')),
                ('mode', models.CharField(choices=[('TEST', 'Test'), ('OFFLINE', 'Offline'), ('AWAIT_LAUNCH', 'Await Launch'), ('DEPLOYMENT', 'Deployment'), ('INITIALIZATION', 'Initialization'), ('CHECKING', 'Checking'), ('NOMINAL', 'Nominal'), ('DETUMBLING', 'Detumbling'), ('SAFE', 'Safe Mode'), ('EMERGENCY', 'Emergency'), ('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Maintenance')], db_index=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['subsystem', 'mode'], name='control_sta_subsyst_fcf21b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], db_index=True, max_length=20)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('raw_data', models.TextField(blank=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('valid', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['subsystem', 'module'], name='control_tel_subsyst_175480_idx'), models.Index(fields=['timestamp', 'subsystem'], name='control_tel_timesta_51114e_idx')],
            },
        ),
    ]
