# Generated by Django 5.1.7 on 2026-05-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_commandmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftwareUpdate',
            new_name='SoftwareUpdateMessage',
        ),
        migrations.RenameIndex(
            model_name='softwareupdatemessage',
            new_name='control_sof_verifie_f0b5ab_idx',
            old_name='control_sof_verifie_f88726_idx',
        ),
    ]
