# Generated by Django 5.1.7 on 2026-01-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('TELEMETRY', 'telemetry'), ('COMMAND', 'command'), ('EVENT', 'event'), ('STATUS', 'status'), ('OTHER', 'other')], default='OTHER', max_length=50)),
                ('data_source', models.CharField(choices=[('GROUND_STATION', 'ground_station'), ('SATELLITE', 'satellite'), ('RADIO_STATION', 'radio_station'), ('OPTICAL_STATION', 'optical_station'), ('FOMALHAUT', 'fomalhaut'), ('OTHER', 'other')], default='OTHER', max_length=50)),
                ('data_destination', models.CharField(choices=[('GROUND_STATION', 'ground_station'), ('SATELLITE', 'satellite'), ('RADIO_STATION', 'radio_station'), ('OPTICAL_STATION', 'optical_station'), ('FOMALHAUT', 'fomalhaut'), ('OTHER', 'other')], default='OTHER', max_length=50)),
                ('content', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FomalhautData',
            fields=[
                ('generaldata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.generaldata')),
                ('category', models.CharField(choices=[('IMAGE', 'image_data'), ('SPECTRAL', 'spectral_data'), ('GENE', 'general')], default='GENE', max_length=50)),
            ],
            bases=('core.generaldata',),
        ),
        migrations.CreateModel(
            name='OpticalStationData',
            fields=[
                ('generaldata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.generaldata')),
                ('category', models.CharField(choices=[('LIGHT', 'light_intensity'), ('GENE', 'general')], default='GENE', max_length=50)),
            ],
            bases=('core.generaldata',),
        ),
        migrations.CreateModel(
            name='RadioStationData',
            fields=[
                ('generaldata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.generaldata')),
                ('category', models.CharField(choices=[('SIGNAL', 'signal_strength'), ('NOISE', 'noise_level'), ('FREQ', 'frequency'), ('GENE', 'general')], default='GENE', max_length=50)),
            ],
            bases=('core.generaldata',),
        ),
        migrations.CreateModel(
            name='SatelliteData',
            fields=[
                ('generaldata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.generaldata')),
                ('category', models.CharField(choices=[('TEMP', 'temperature'), ('POWR', 'power'), ('HUMI', 'humidity'), ('POSI', 'position'), ('GENE', 'general')], default='GENE', max_length=50)),
            ],
            bases=('core.generaldata',),
        ),
    ]
