# Generated by Django 5.1.7 on 2026-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('TC', 'Telecommand'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=10)),
                ('parameters', models.JSONField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('command_type', models.CharField(choices=[('CHANGE_MODE', 'Change Mode'), ('PAYLOAD_POWER', 'Payload Power'), ('ADCS_CONTROL', 'Adcs Control'), ('TAKE_PICTURE', 'Take Picture'), ('THERMAL_CONTROL', 'Thermal Control'), ('POWER_LINE', 'Power Line'), ('DEPLOY_ANTENNA', 'Deploy Antenna'), ('RECALIBRATE_SENSOR', 'Recalibrate Sensor'), ('SOFTWARE_UPDATE', 'Software Update')], max_length=30)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('TC', 'Telecommand'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=10)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('raw_data', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('TC', 'Telecommand'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('versión', models.CharField(max_length=20)),
                ('checksum', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('TC', 'Telecommand'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=10)),
                ('state', models.JSONField()),
                ('mode', models.CharField(choices=[('TEST', 'Test'), ('OFFLINE', 'Offline'), ('AWAIT_LAUNCH', 'Await Launch'), ('DEPLOYMENT', 'Deployment'), ('INITIALIZATION', 'Initialization'), ('CHECKING', 'Checking'), ('NOMINAL', 'Nominal'), ('DETUMBLING', 'Detumbling'), ('SAFE', 'Safe'), ('EMERGENCY', 'Emergency'), ('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TM', 'Telemetry'), ('TC', 'Telecommand'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('destination', models.CharField(choices=[('SATELLITE', 'Satellite'), ('GROUND', 'Ground Station'), ('RADIO', 'Radio Station'), ('OPTICAL', 'Optical Station'), ('FOMALHAUT', 'Central Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=10)),
                ('parameter', models.CharField(max_length=50)),
                ('raw_data', models.TextField(blank=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='satellitedata',
            name='generaldata_ptr',
        ),
        migrations.RemoveField(
            model_name='opticalstationdata',
            name='generaldata_ptr',
        ),
        migrations.RemoveField(
            model_name='radiostationdata',
            name='generaldata_ptr',
        ),
        migrations.DeleteModel(
            name='FomalhautData',
        ),
        migrations.DeleteModel(
            name='SatelliteData',
        ),
        migrations.DeleteModel(
            name='OpticalStationData',
        ),
        migrations.DeleteModel(
            name='GeneralData',
        ),
        migrations.DeleteModel(
            name='RadioStationData',
        ),
    ]
