# Generated by Django 5.1.7 on 2026-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commandmessage_eventmessage_softwareupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetrymessage',
            old_name='parameter',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='message_type',
            field=models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2),
        ),
        migrations.AlterField(
            model_name='eventmessage',
            name='message_type',
            field=models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2),
        ),
        migrations.AlterField(
            model_name='softwareupdate',
            name='message_type',
            field=models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='message_type',
            field=models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2),
        ),
        migrations.AlterField(
            model_name='telemetrymessage',
            name='message_type',
            field=models.CharField(choices=[('TM', 'Telemetry'), ('CM', 'Command'), ('EV', 'Event'), ('ST', 'Status'), ('UP', 'Software Update')], max_length=2),
        ),
    ]
