# Generated by Django 5.1.7 on 2026-02-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_parameter_telemetrymessage_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmessage',
            name='raw_data',
        ),
    ]
