# Generated by Django 5.1.7 on 2026-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_eventmessage_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmessage',
            name='subsystem',
            field=models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmessage',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmessage',
            name='subsystem',
            field=models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='subsystem',
            field=models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telemetrymessage',
            name='subsystem',
            field=models.CharField(choices=[('EPS', 'Electrical Power System'), ('ADCS', 'Attitude Control'), ('THERMAL', 'Thermal Control'), ('COMMS', 'Communications'), ('PAYLOAD', 'Payload'), ('OBC', 'On Board Computer'), ('GENERAL', 'General')], max_length=20),
        ),
    ]
