# Generated by Django 5.1.7 on 2026-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_commandmessage_subsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmessage',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10),
        ),
    ]
