# Generated by Django 5.1.7 on 2026-05-08 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, help_text='Image format (PNG, JPEG, etc.)', max_length=10, null=True)),
                ('header', models.TextField(blank=True, help_text='Image header metadata', null=True)),
                ('exif', models.TextField(blank=True, help_text='EXIF data as JSON string', null=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Original capture date/time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('raw_data', models.TextField(help_text='Raw image data or reference')),
                ('content', models.ImageField(blank=True, default=None, help_text='Uploaded image file', null=True, upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'tiff', 'bmp'])])),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='imaging_ima_created_790ebc_idx'), models.Index(fields=['format'], name='imaging_ima_format_fdfc37_idx'), models.Index(fields=['fecha'], name='imaging_ima_fecha_732fcb_idx')],
            },
        ),
    ]
