# Generated by Django 5.1.7 on 2026-05-12 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation timestamp'),
        ),
    ]
