# Generated by Django 5.1.7 on 2025-03-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitedata',
            name='raw_data',
            field=models.TextField(default=''),
        ),
    ]
