# Generated by Django 5.1.7 on 2025-04-10 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0003_alter_satellitedata_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitedata',
            name='category',
            field=models.CharField(choices=[('TEMP', 'Temperature'), ('POWR', 'Power'), ('HUMI', 'Humidity'), ('POSI', 'Position'), ('GENE', 'General')], default='GENE', help_text='Category of the satellite data (e.g., temperature, power).', max_length=50),
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='content',
            field=models.JSONField(blank=True, help_text='JSON data representing satellite readings or metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='raw_data',
            field=models.TextField(default='', help_text='Raw textual representation of the satellite data.'),
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Timestamp for when the data was recorded.', null=True),
        ),
    ]
