# Generated by Django 5.1.7 on 2025-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0004_alter_satellitedata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitedata',
            name='content',
            field=models.JSONField(blank=True, default='', help_text='JSON data representing satellite readings or metadata.'),
        ),
    ]
