# Generated by Django 5.1.7 on 2025-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0005_alter_satellitedata_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitedata',
            name='category',
            field=models.CharField(choices=[('TEMP', 'temperature'), ('POWR', 'power'), ('HUMI', 'humidity'), ('POSI', 'position'), ('GENE', 'general')], default='GENE', max_length=50),
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='raw_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='satellitedata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
