# Generated by Django 5.1.7 on 2026-01-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0006_alter_satellitedata_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SatelliteData',
        ),
    ]
