# Generated by Django 5.1.7 on 2026-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the log entry was created')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, help_text='Log severity level', max_length=10)),
                ('logger', models.CharField(db_index=True, help_text="Logger name (e.g., 'ground-stations-central-server')", max_length=100)),
                ('module', models.CharField(db_index=True, help_text='Source module/file name', max_length=100)),
                ('function', models.CharField(help_text='Function/method name', max_length=100)),
                ('message', models.TextField(help_text='Log message content')),
                ('request_method', models.CharField(blank=True, help_text='HTTP method', max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, db_index=True, help_text='Request URL path', max_length=255, null=True)),
                ('request_status_code', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('request_client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('request_user', models.CharField(blank=True, help_text='Authenticated username', max_length=100, null=True)),
                ('exception_type', models.CharField(blank=True, db_index=True, help_text='Exception class name', max_length=100, null=True)),
                ('exception_message', models.TextField(blank=True, help_text='Exception message', null=True)),
                ('exception_stack_trace', models.TextField(blank=True, help_text='Full stack trace', null=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Any additional structured data', null=True)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'level'], name='audit_logen_timesta_5e8fbd_idx'), models.Index(fields=['logger', 'timestamp'], name='audit_logen_logger_b5887d_idx'), models.Index(fields=['module', 'function'], name='audit_logen_module_36c1e7_idx'), models.Index(fields=['exception_type'], name='audit_logen_excepti_5006b9_idx'), models.Index(fields=['request_path'], name='audit_logen_request_7d1958_idx')],
            },
        ),
    ]
