# Generated by Django 5.1.7 on 2025-03-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
