# Generated by Django 5.1.7 on 2025-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_image', '0002_alter_imagen_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='content',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
